### ISSUE TITLE
Can't Debug with 2023.1

### ISSUE THREAD

**Issue by boristsr** [BlackStartx/PyCharm-Blender-Plugin#14]
Hi, Love this tool!

I wanted to report that since upgrading to 2023.1 I can't press the debug icon next to my chosen blender instance. I get the stack trace listed at the bottom.

![image](https://user-images.githubusercontent.com/2999162/235032201-c5255a22-2546-4d95-ab9c-7d7d71b9e391.png)

Clicking Run works. 
![image](https://user-images.githubusercontent.com/2999162/235032167-c00ed377-ab6f-47ed-a568-c0b3607385ad.png)

I'm running the following versions:
PyCharm 2023.1 - Build #PY-231.8109.197, built on March 30, 2023
Blend-Charm 2023.1

```
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "ui.tool_window.BlenderToolWindow.getSelectedBlenderInstance().addonPath" is null
	at ui.tool_window.BlenderToolWindow$3.<init>(BlenderToolWindow.java:398)
	at ui.tool_window.BlenderToolWindow.onDebugClick(BlenderToolWindow.java:397)
	at util.MySwingUtil$1.mouseClicked(MySwingUtil.java:15)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6659)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6421)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4584)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:614)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:569)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by boristsr** [comment]
Also for additional information:
 - I deleted all instances of `BlendCharmSettings.xml` i could find on my system
 - I deleted the .idea folder from my project
 - I uninstalled and reinstalled BlendCharm from the plugins page of PyCharm

**Comment by BlackStartx** [comment]
Hi Boristsr~

Thanks so much for the report!

That was due to a last time feature I've shipped with 2023.1 that fixes the file of the debug breakpoints, but I forgot that in some scenarios it may be uninitialised~

I'll push a fix right away!

**Comment by BlackStartx** [comment]
By the way, after further testing it seems that pressing the "Run" button will initialise the field and prevent further exceptions.

**Comment by boristsr** [comment]
Oh wow! Can confirm that workaround does work. Dunno how I missed that! Thanks!

**Comment by BlackStartx** [comment]
Small update: I've fixed this in the latest commits, I'll handle #13 too and publish a public release soon~ (Hopefully today) :3
